_BASE_RUN: ../../../pool/run/training/soccer/finetune_soccer.yaml
_BASE_MODEL: ../../../pool/backbone/soccer/tadaformer_l14_soccer.yaml


DATA:
  DATA_ROOT_DIR: /sc/home/konrad.goldenbaum/data/SoccerData/mvfouls
  ANNO_DIR:
  WEIGHTED_LOSS: true
  CLASS_WEIGHTS:
    TYPE: 2.0
    SEVERITY: 1.0
  SAMPLING_MODE: segment_based
  NUM_INPUT_FRAMES: 16
  TAKE_NUM_FRAMES: 16
  NUM_VIEWS: 2
  TRAIN_JITTER_SCALES: [0.08, 1.0]
  TRAIN_CROP_SIZE: 224
  TEST_SCALE: 224
  TEST_CROP_SIZE: 224
  MEAN: [0.48145466, 0.4578275, 0.40821073]
  STD: [0.26862954, 0.26130258, 0.27577711]
VIDEO:
  HEAD:
    NUM_CLASSES:
      TYPE: 9
      SEVERITY: 4
    DROPOUT_RATE: 0

OPTIMIZER:
  BASE_LR: 2e-4
  ADJUST_LR: true
  LR_POLICY: cosine_v2
  COSINE_END_LR: 1e-6
  COSINE_AFTER_WARMUP: true
  MAX_EPOCH: 12
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.05
  WARMUP_EPOCHS: 2
  WARMUP_START_LR: 1e-6
  OPTIM_METHOD: adamw
  DAMPENING: 0.0
  NESTEROV: true
  HEAD_LRMULT: 10
  NEW_PARAMS: ["tada"]
  NEW_PARAMS_MULT: 10
  LAYER_WISE_LR_DECAY: 0.85
AUGMENTATION: 
  COLOR_AUG: true
  GRAYSCALE: 0.2
  COLOR_P: 0.0
  CONSISTENT: true
  SHUFFLE: true
  GRAY_FIRST: false
  IS_SPLIT: false
  USE_GPU: true
  SSV2_FLIP: true
  RATIO: [0.75, 1.333]
  MIXUP: 
    ENABLE: false
  CUTMIX: 
    ENABLE: false
  RANDOM_ERASING:
    ENABLE: false
  LABEL_SMOOTHING: 0.1
  AUTOAUGMENT:
    ENABLE: true
    BEFORE_CROP: true
    TYPE: rand-m9-n4-mstd0.5-inc1
NUM_GPUS: 2
DATA_LOADER:
  NUM_WORKERS: 2
  PIN_MEMORY: false

TRAIN:
  ENABLE: true
  DATASET: MVFoul                    # !!@1
  BATCH_SIZE: 4
  LOG_FILE: training_log.log
  LOSS_FUNC: cross_entropy
  EVAL_PERIOD: 4
  NUM_FOLDS: 1
  AUTO_RESUME: true
  CHECKPOINT_PERIOD: 2
  CHECKPOINT_FILE_PATH: "/sc/home/konrad.goldenbaum/thesis/replicate_MVF/ckpts/checkpoints/checkpoint_epoch_00002.pyth"    # !!@2
  CHECKPOINT_TYPE: pytorch
  CHECKPOINT_INFLATE: false
  FINE_TUNE: true
  ONLY_LINEAR: false

TEST:
  ENABLE: true                     # !!@3
  DATASET: Mvfoul                         # !!@3
  BATCH_SIZE: 8
  NUM_SPATIAL_CROPS: 1
  SPATIAL_CROPS: cc
  NUM_ENSEMBLE_VIEWS: 1
  LOG_FILE: val.log
  CHECKPOINT_FILE_PATH: "/sc/home/konrad.goldenbaum/l14_clip_k710.pyth"
  CHECKPOINT_TYPE: pytorch
  AUTOMATIC_MULTI_SCALE_TEST: true

WANDB:
  SYNC_ENABLE: true
  ENTITY_NAME: "konradgoldenbaum-hasso-plattner-institut"
  PROJECT_NAME: "Thesis-Goldenbaum"