TEST:
  ENABLE: true
  DATASET: MVFoul
  BATCH_SIZE: 32
  LOG_FILE: test_log.log
DATA:
  DATA_ROOT_DIR: /sc/home/konrad.goldenbaum/data/SoccerData/mvfouls
  ANNO_DIR:
  WEIGHTED_LOSS: false
  SAMPLING_MODE: segment_based
  NUM_INPUT_FRAMES: 16
  TAKE_NUM_FRAMES: 64
  NUM_VIEWS: 4
  TRAIN_JITTER_SCALES: [0.08, 1.0]
  TRAIN_CROP_SIZE: 224
  TEST_SCALE: 224
  TEST_CROP_SIZE: 224
  MEAN: [0.48145466, 0.4578275, 0.40821073]
  STD: [0.26862954, 0.26130258, 0.27577711]
  CENTER_FRAME: 75
    

NUM_GPUS: 2
RANDOM_SEED: 42
DATA_LOADER:
  NUM_WORKERS: 1
  PIN_MEMORY: false

MODEL:
  NAME: FOULVideoModel
  
VIDEO:
  BACKBONE:
    META_ARCH: FOULVisionTransformer
    INPUT_RES: 224
    PATCH_SIZE: 14
    TUBLET_SIZE: 3
    TUBLET_STRIDE: 2
    NUM_FEATURES: 1024
    NUM_OUT_FEATURES: 1024
    DEPTH: 24
    NUM_HEADS: 16
    DROP_PATH: 0.0
    ATTN_DROPOUT: 0.0
    REQUIRE_PROJ: false
    ATTN_MASK_ENABLE: false
    DOUBLE_TADA: false
    FREEZE: true
    REDUCTION: 2
    PREAGGREGATE:
      ENABLE: false
      NAME: TemporalPooling
    BRANCH: 
      NAME: TAdaFormerBlock
      ROUTE_FUNC_K: [3, 3]
      ROUTE_FUNC_R: 2
    TEMP_ENHANCE: false
  HEAD:
    NAME: FOULHead
    OUTPUT_DIM: 512
    NUM_CLASSES:
      TYPE: 9
      SEVERITY: 4
    DROPOUT_RATE: 0
  TIME_PROCESSOR:
    NAME: TemporalConv
    NUM_LAYERS: 1
    KERNEL_SIZE: 3
    DILATION: 1

WANDB:
  SYNC_ENABLE: true
  ENTITY_NAME: "konradgoldenbaum-hasso-plattner-institut"
  PROJECT_NAME: "Thesis-Goldenbaum"

HUGGINGFACE:
  LOAD: true
  REPO: "KGolden/mvf_checkpoints"
  CACHE_DIR: "./hf_cache"
  LOAD_NAME: "head_temp"