PRETRAIN:
  ENABLE: false
DATA:
  DATA_ROOT_DIR: 
  ANNO_DIR: 
  NUM_INPUT_FRAMES: 16
  NUM_INPUT_CHANNELS: 3
  SAMPLING_MODE: interval_based
  SAMPLING_RATE: 4
  TRAIN_JITTER_SCALES: [168, 224]
  TRAIN_CROP_SIZE: 112
  TEST_SCALE: 224
  TEST_CROP_SIZE: 112
  MEAN: [0.45, 0.45, 0.45]
  STD: [0.225, 0.225, 0.225]
  MULTI_LABEL: false
  ENSEMBLE_METHOD: sum
  FPS: 25
  TARGET_FPS: 25
  CENTER_FRAME: 75
OPTIMIZER:
  BASE_LR: 0.002
  LR_POLICY: cosine
  MAX_EPOCH: 12
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-3
  WARMUP_EPOCHS: 2
  WARMUP_START_LR: 0.0002
  OPTIM_METHOD: adam
  DAMPENING: 0.0
  NESTEROV: true
BN:
  FREEZE: false
  WEIGHT_DECAY: 0.0
  EPS: 1e-3
DATA_LOADER:
  NUM_WORKERS: 2
  PIN_MEMORY: false
  ENABLE_MULTI_THREAD_DECODE: true
NUM_GPUS: 2
SHARD_ID: 0
NUM_SHARDS: 1
RANDOM_SEED: 0
OUTPUT_DIR: "/sc/home/konrad.goldenbaum/thesis/replicate_MVF/ckpts/checkpoints_backbone_no_temp"
HUGGINGFACE:
  LOAD: false
  REPO: "KGolden/mvf_checkpoints"
  SAVE: true
  CACHE_DIR: "./hf_cache"
  SAVE_NAME: "backbone_finetuned"
OUTPUT_CFG_FILE: configuration.log
LOG_PERIOD: 4
DIST_BACKEND: nccl
LOG_MODEL_INFO: true
LOG_CONFIG_INFO: true
AUGMENTATION:
  COLOR_AUG: true
  BRIGHTNESS: 0.5
  CONTRAST: 0.5
  SATURATION: 0.5
  HUE: 0.25
  GRAYSCALE: 0.3
  CONSISTENT: true
  SHUFFLE: true
  GRAY_FIRST: true
  RATIO: [0.857142857142857, 1.1666666666666667]
  USE_GPU: true
PAI: false

